services:
  - type: worker
    name: echobrainbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        sync: false  # Il token sarà impostato manualmente su Render
